name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: action/checkout@v2
      - name: use node js ${{ matrix.node-version }}
        uses: action/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run ci:test